spring.datasource.url=jdbc:postgresql://localhost:4010/bitcoin_payments
spring.datasource.username=bitcoin
spring.datasource.password=bitcoin
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.root=WARN
logging.level.com.yourcompany.bitcoinpayment=INFO
